### ISSUE TITLE
sbt-mode gets confused when test sends output after "completing"

### ISSUE THREAD

**Issue by greenrd** [hvesalai/sbt-mode#28]
If I use Akka in a ScalaTest test, Akka may shut down and print a log message about its shutdown after sbt thinks the test has finished and has returned to its command line. If that happens, and then I use C-k to delete the offending log message, sbt-mode gets very confused, and neither lets me recall previous commands with M-p nor run new commands with the Enter key.

**Comment by hvesalai** [comment]
Yeah.. This is a so-called known problem. When sbt-mode doesn't see the prompt as the last line, it goes in to read-only mode.

You can recover with `sbt-clear` which is normally bound to `C-c l`

**Comment by greenrd** [comment]
I must say I think this is a poor attitude to usability to mark this as a question instead of a bug. Is there any law that says that emacs software has to be hard to use? Magit isn't, for example.

**Comment by hvesalai** [comment]
I'm sorry for my terse answer and the flags. 

There really isn't anything simple that I can do to fix this. Since the dawn of command line it has been the prompt that has indicated that the command interpreter is again ready to receive user input. It is based on this assumption I have coded sbt-mode not to allow user input before the prompt is seen on the last line of the buffer. If there is bad software, such as play, that breaks this rule and emits output after the prompt, then there is really nothing to be done. In my opinion it is play that needs to be fixed.

If you think that my mode is broken and that it should allow user input even though there is no prompt, then you need to disable the guard I have coded into it. You can do this simply by adding the following into your emacs init (usually `~/.emacs` or `~/.emacs.d/init`).

```lisp
(add-hook 'sbt-mode-hook '(lambda ()
  (setq-local comint-prompt-read-only nil)
))
```
